brew: update backblaze upgrade script
- zsh: update backblaze upgrade script to return a non-zero exit code
  when the upgrade fails

diff --git a/scripts/zsh/upgrade-backblaze b/scripts/zsh/upgrade-backblaze
--- a/scripts/zsh/upgrade-backblaze
+++ b/scripts/zsh/upgrade-backblaze
@@ -38,7 +38,7 @@ function upgrade-backblaze {
 
   echo "==> Performing upgrade..."
   # perform upgrade
-  sudo "$caskroom/backblaze/$version/Backblaze Installer.app/Contents/MacOS/bzinstall_mate" -upgrade bzdiy
+  sudo "$caskroom/backblaze/$version/Backblaze Installer.app/Contents/MacOS/bzinstall_mate" -upgrade bzdiy || (echo "==> Upgrade failed" && return 1)
   echo "==> Upgrade successful"
 
   echo "==> Marking Backblaze Cask as upgraded in Homebrew metadata..."
